/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"libhack"
#define VCS_UUID		"9156326fc1af8274445475661bc0c19952a515f4"
#define VCS_NUM			59
#define VCS_DATE		"2020-10-24T21:18:38Z"
#define VCS_BRANCH		"dev"
#define VCS_TAG			"v0.1"
#define VCS_TAG_OPENPGP	""
#define VCS_TICK		54
#define VCS_EXTRA		""

#define VCS_ACTION_STAMP	"2020-10-24T21:18:38Z!lucas.engen.cc@gmail.com"
#define VCS_FULL_HASH		"3dcd4a34ca76e2037c025bcdf2c90d4e3211da86"
#define VCS_COMMIT_OPENPGP	"363DA20EA449B53085CD4A466512BE6BAE730817"
#define VCS_SHORT_HASH		"3dcd4a3"

#define VCS_WC_MODIFIED		1

#endif

/* end */
