name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.systems }}
    strategy:
      matrix:
        systems: [windows-latest,windows-2019]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate revision information
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/Autorevision/autorevision/master/autorevision.sh -o autorevision
        chmod +x autorevision
        ./autorevision -t h > autorevision.h

    - name: Configure CMake
      run: cmake -G "MinGW Makefiles" -S . -B build -DCMAKE_BUILD_TYPE=Release -DLIBHACK_BUILD_EXAMPLES=ON

    - name: Build library and examples
      run: cmake --build build --parallel

    - name: Run tests
      run: cmake --build build --target test
