name: Build - Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -G "MinGW Makefiles" -B build

    - name: Generate revision information
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/Autorevision/autorevision/master/autorevision.sh -o autorevision
        ./autorevision -t h > autorevision.h

    - name: Build libhack
      run: make
      working-directory: build

    - name: Configure CMake (examples)
      run: |
        cp ../../../build/*.dll libhack.dll
        cp ../../../build/*.a libhack.a
        cmake -G "MinGW Makefiles" -B build
      working-directory: src/examples/windows

    - name: Build examples
      run: make
      working-directory: src/examples/windows/build
