name: Build - Linux

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -G "Unix Makefiles" -B build

    - name: Generate revision information
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/Autorevision/autorevision/master/autorevision.sh -o autorevision
        ./autorevision -t h > autorevision.h

    - name: Build libhack
      run: make
      working-directory: build

    - name: Configure CMake (examples)
      run: |
        cp ../../build/*.so libhack.so
        cp ../../build/*.a libhack.a
        cmake -G "MinGW Makefiles" -B build
      working-directory: src/examples

    - name: Build examples
      run: make
      working-directory: src/examples/build
