name: SonarQube Cloud

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: sonar-linux-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and analyze (Linux)
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v8.1.0

      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y autorevision libprocps-dev
          autorevision -t h > autorevision.h
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DLIBHACK_ENABLE_COVERAGE=ON

      - name: Run build-wrapper
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/ --config Debug

      - name: Run tests to generate coverage statistics
        run: |
          cmake --build build --target test

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: SonarSource/sonarqube-scan-action@v8.1.0
        with:
          args: >
            --define "sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
